import express from 'express';
import { Fetch3D } from '@pikal6/3dfetch';

const app = express();
const port = Number(process.env.PORT || 8787);
const LIMIT = Number(process.env.SEARCH_LIMIT || 12);
const PROVIDER_LIMIT = Math.max(LIMIT, 30);
const TIMEOUT_MS = Number(process.env.HTTP_TIMEOUT_MS || 15000);
const FORMATS = new Set(['gltf','glb','obj','fbx','blend','usd','usdz','stl','3mf','dae','ply','step','iges','off','max','c4d','ma','mb','abc','3ds','maya','fb']);
const ALIAS = { stp:'step', igs:'iges', blender:'blend' };
const PRIORITY = { polypizza:120, free3d:115, polyhaven:105, printables:100, sketchfab:90, smithsonian:85, nasa:80, '3dfetch-fallback':50 };

function normFormat(value) { const key=String(value||'').trim().toLowerCase().replace(/^\./,''); return ALIAS[key]||key; }
function parseQuery(raw='') { const parts=raw.trim().split(/\s+/).filter(Boolean); let format=null; const kept=[]; for(const part of parts){const key=normFormat(part); if(!format&&FORMATS.has(key)) format=key; else kept.push(part);} return {query:kept.join(' ').trim(),format}; }

async function fetchJson(url, options={}) { const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),TIMEOUT_MS); try { const response=await fetch(url,{...options,signal:controller.signal}); if(!response.ok) throw new Error(`HTTP ${response.status} ${response.statusText}`); return await response.json(); } finally { clearTimeout(timer); } }

function normalize(item,source) { if(!item)return null; const formats=Array.isArray(item.formats)?[...new Set(item.formats.map(normFormat).filter(Boolean))]:[]; return {name:String(item.name||item.title||'Без названия').trim(),source,sourceUrl:item.sourceUrl||item.viewerUrl||item.url||'',thumbnail:item.thumbnail||item.thumbnailUrl||null,formats,license:item.license||null,access:item.access||null,text:item.text||''}; }
function relevanceScore(item,query) { const terms=query.toLowerCase().split(/\s+/).filter(Boolean); const name=String(item.name||'').toLowerCase(); const text=`${item.name||''} ${item.text||''}`.toLowerCase(); let score=0; for(const term of terms){ if(name===term)score+=140; else if(name.startsWith(term))score+=110; else if(name.includes(term))score+=80; else if(text.includes(term))score+=25; else return -1; } if(name===query.toLowerCase())score+=100; return score; }
function rank(results,query,format){ const seen=new Set(); return results.map(item=>({...item,relevance:relevanceScore(item,query),providerPriority:PRIORITY[item.source]||40})).filter(item=>item.relevance>=0).filter(item=>!format||item.formats.includes(format)).filter(item=>{const k=`${item.source}:${item.sourceUrl||item.name}`;if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>b.relevance-a.relevance||b.providerPriority-a.providerPriority||a.name.localeCompare(b.name)).slice(0,LIMIT); }

async function searchPrintables(query,format){ if(format&&format!=='stl')return []; const body={query:`query SearchPrints($query: String!, $limit: Int, $ordering: SearchChoicesEnum) { searchPrints2(query: $query, printType: print, limit: $limit, ordering: $ordering) { items { id name slug license { id name } stls { id name fileSize filePreviewPath } } } }`,variables:{query,limit:PROVIDER_LIMIT,ordering:'best_match'}}; const data=await fetchJson('https://api.printables.com/graphql/',{method:'POST',headers:{'content-type':'application/json','user-agent':'3DModelFinderBot/1.0'},body:JSON.stringify(body)}); if(data.errors?.length)throw new Error(data.errors.map(e=>e.message).join('; ')); return (data?.data?.searchPrints2?.items||[]).filter(x=>x.stls?.length).map(x=>normalize({name:x.name,sourceUrl:`https://www.printables.com/model/${x.id}-${x.slug}`,formats:['stl'],license:x.license?.name||null},'printables')); }

async function searchPolyPizza(query,format){ const key=process.env.POLY_PIZZA_KEY; if(!key|| (format&&!['glb','fbx','obj'].includes(format)))return []; const params=new URLSearchParams({limit:String(PROVIDER_LIMIT)}); if(format)params.set('format',format); const data=await fetchJson(`https://api.poly.pizza/v1/search/${encodeURIComponent(query)}?${params}`,{headers:{'X-Auth-Token':key,'User-Agent':'3DModelFinderBot/1.0'}}); const rows=data?.results||data?.items||data?.data||[]; return rows.map(item=>{const formats=[]; if(item.Download)formats.push('glb'); if(item.DownloadFBX)formats.push('fbx'); if(item.DownloadOBJ)formats.push('obj'); return normalize({name:item.Title||item.title||item.name,sourceUrl:item.URL||item.url||`https://poly.pizza/m/${item.ID||item.id}`,thumbnailUrl:item.Thumbnail||item.thumbnail,formats,license:item.Licence||item.license,text:`${item.Description||''} ${(item.Tags||item.tags||[]).join(' ')}`},'polypizza');}).filter(x=>x?.name&&x.formats.length&&(!format||x.formats.includes(format))); }

async function searchFree3D(query,format){ if(format&&!['fbx','glb','obj','stl','max','blend','c4d','abc'].includes(format))return []; const params=new URLSearchParams({q:query,limit:String(PROVIDER_LIMIT)}); if(format)params.set('format',format); try { const data=await fetchJson(`https://free3d.online/api-embeddings/?${params}`,{headers:{Accept:'application/json','User-Agent':'3DModelFinderBot/1.0'}}); const rows=Array.isArray(data)?data:(data.results||data.items||data.data||[]); return rows.map(item=>normalize({name:item.name||item.title||item.nameText,sourceUrl:item.modelPageUrl||item.modelUrl||item.url||(item.slug?`https://free3d.online/model/${item.slug}`:''),thumbnailUrl:item.thumbnail||item.thumbnailUrl||item.previewMediumUrl||item.preview,formats:Array.isArray(item.formats)?item.formats:(item.available_formats||'').split(/[ ,|]+/).filter(Boolean),license:item.license||null,text:[item.description,item.category,item.subcategory,...(item.keywords||[])].filter(Boolean).join(' ')},'free3d')).filter(x=>x?.name&&x.sourceUrl&&(!format||x.formats.includes(format))); } catch(e){console.error('free3d search:',e.message);return [];} }

async function searchSketchfab(query,format){ const params=new URLSearchParams({q:query,type:'models',limit:String(PROVIDER_LIMIT),sort_by:'-relevance'}); const headers=process.env.SKETCHFAB_API_TOKEN?{Authorization:`Token ${process.env.SKETCHFAB_API_TOKEN}`}:{ }; const data=await fetchJson(`https://api.sketchfab.com/v3/search?${params}`,{headers}); return (data.results||[]).map(item=>normalize({name:item.name,sourceUrl:item.viewerUrl,thumbnailUrl:item.thumbnails?.images?.[0]?.url,formats:item.formats,license:item.license?.label||null,text:`${item.description||''} ${(item.tags||[]).join(' ')}`},'sketchfab')).filter(x=>!format||x.formats.includes(format)); }

let polyhavenCache=null,polyhavenCacheAt=0;
async function searchPolyHaven(query,format){ const supported=['blend','fbx','gltf','obj','usd']; if(format&&!supported.includes(format))return []; if(!polyhavenCache||Date.now()-polyhavenCacheAt>1800000){polyhavenCache=await fetchJson('https://api.polyhaven.com/assets?type=models',{headers:{'User-Agent':'3DModelFinderBot/1.0'}});polyhavenCacheAt=Date.now();} const terms=query.toLowerCase().split(/\s+/).filter(Boolean); return Object.entries(polyhavenCache).filter(([id,item])=>{const hay=[id,item.name,item.description,...(item.tags||[]),item.category].filter(Boolean).join(' ').toLowerCase();return terms.every(t=>hay.includes(t));}).slice(0,PROVIDER_LIMIT).map(([id,item])=>normalize({name:item.name||id,sourceUrl:`https://polyhaven.com/a/${id}`,thumbnailUrl:item.thumbnail_url,formats:supported,license:'CC0',text:`${item.name||''} ${(item.tags||[]).join(' ')}`},'polyhaven')).filter(x=>!format||x.formats.includes(format)); }

let nasaTree=null,nasaTreeAt=0;
async function searchNasa(query,format){ const supported=['3ds','blend','fb','glb','max','maya','stl']; if(format&&!supported.includes(format))return []; if(!nasaTree||Date.now()-nasaTreeAt>1800000){const data=await fetchJson('https://api.github.com/repos/nasa/NASA-3D-Resources/git/trees/master?recursive=1',{headers:{Accept:'application/vnd.github+json','User-Agent':'3DModelFinderBot/1.0'}});nasaTree=Array.isArray(data.tree)?data.tree:[];nasaTreeAt=Date.now();} const terms=query.toLowerCase().split(/\s+/).filter(Boolean),groups=new Map(); for(const entry of nasaTree){if(entry.type!=='blob')continue;const m=entry.path.match(/^3D Models\/([^/]+)\/(.+)$/i);if(!m)continue;const rel=m[2],ext=rel.includes('.')?rel.split('.').pop().toLowerCase():'';const fmt=ext==='blender'?'blend':ext;if(!supported.includes(fmt)||!terms.every(t=>`${m[1]} ${rel}`.toLowerCase().includes(t)))continue;if(!groups.has(m[1]))groups.set(m[1],new Set());groups.get(m[1]).add(fmt);} return [...groups.entries()].slice(0,LIMIT).map(([name,formats])=>normalize({name,sourceUrl:`https://github.com/nasa/NASA-3D-Resources/tree/master/3D%20Models/${encodeURIComponent(name)}`,formats:[...formats],license:'NASA Media Usage Guidelines'},'nasa')).filter(x=>!format||x.formats.includes(format)); }

async function searchSmithsonian(query,format){const key=process.env.SMITHSONIAN_API_KEY;if(!key)return [];const params=new URLSearchParams({q:query,rows:String(PROVIDER_LIMIT),api_key:key});if(format)params.set('model_type',format);const data=await fetchJson(`https://3d-api.si.edu/api/3d/v1/search?${params}`);return(data?.rows||data?.results||[]).map(item=>normalize({name:item.name||item.title,sourceUrl:item.url||item.sourceUrl||item._links?.self?.href||'',thumbnailUrl:item.thumbnail,formats:item.model_type?[normFormat(item.model_type)]:[],license:item.license||'Smithsonian Open Access'},'smithsonian')).filter(x=>!format||x.formats.includes(format));}

let fetch3d=null;try{fetch3d=new Fetch3D({timeout:TIMEOUT_MS});}catch(e){console.error('3dfetch unavailable:',e.message);}
async function searchFallback(query,format){if(!fetch3d)return [];try{const result=await fetch3d.searchAll(format?{query,formats:[format],limit:PROVIDER_LIMIT}:{query,limit:PROVIDER_LIMIT});return(result?.models||[]).map(x=>normalize(x,x.source||'3dfetch-fallback')).filter(x=>!format||x.formats.includes(format));}catch(e){console.error('3dfetch fallback:',e.message);return[];}}

async function searchModels(query,format){const providers=[['printables',searchPrintables],['polypizza',searchPolyPizza],['free3d',searchFree3D],['sketchfab',searchSketchfab],['polyhaven',searchPolyHaven],['nasa',searchNasa],['smithsonian',searchSmithsonian]];const settled=await Promise.allSettled(providers.map(([,fn])=>fn(query,format)));let all=[];settled.forEach((r,i)=>{if(r.status==='fulfilled')all.push(...r.value);else console.error(`${providers[i][0]} failed:`,r.reason?.message||r.reason);});all.push(...await searchFallback(query,format));return rank(all,query,format);}

let threeDDDLatest=null,threeDDDAt=0;
async function get3DDDLatest(){if(threeDDDLatest&&Date.now()-threeDDDAt<1800000)return threeDDDLatest;const data=await fetchJson('https://models.3ddd.ru/api/models/last',{method:'POST',headers:{'content-type':'application/json',accept:'application/json','user-agent':'3DModelFinderBot/1.0 (+link-only)'},body:'{}'});if(!data?.success||!Array.isArray(data.data))throw new Error('Unexpected 3DDD response');threeDDDLatest=data.data.map(item=>normalize({name:item.title||item.titleEn||item.slug,sourceUrl:`https://3ddd.ru/3dmodels/show/${item.slug}`,thumbnailUrl:item.image?`https://3ddd.ru/${String(item.image).replace(/^\//,'')}`:null,formats:[],license:item.typeText==='pro'?'PRO on 3DDD':item.typeText==='free'?'FREE on 3DDD':null,access:'link-only'},'3ddd'));threeDDDAt=Date.now();return threeDDDLatest;}

app.get('/health',(_req,res)=>res.json({ok:true,service:'3d-model-finder-search',directProviders:['printables','polypizza','free3d','sketchfab','polyhaven','nasa','3ddd',...(process.env.SMITHSONIAN_API_KEY?['smithsonian']:[])],fallback:'3dfetch',configured:{polypizza:Boolean(process.env.POLY_PIZZA_KEY),sketchfab:Boolean(process.env.SKETCHFAB_API_TOKEN),smithsonian:Boolean(process.env.SMITHSONIAN_API_KEY)},threeDFetchLoaded:Boolean(fetch3d)}));
app.get('/providers',(_req,res)=>res.json({providers:[{name:'polypizza',mode:'direct',formats:['glb','fbx','obj'],auth:'api-key',configured:Boolean(process.env.POLY_PIZZA_KEY)},{name:'free3d',mode:'direct-public',formats:['fbx','glb','obj','stl','max','blend','c4d','abc'],auth:'public-discovery'},{name:'polyhaven',mode:'direct',formats:['blend','fbx','gltf','obj','usd'],auth:'none'},{name:'sketchfab',mode:'catalog',formats:['glb','gltf','usd','usdz','obj','fbx'],auth:'optional-token'},{name:'nasa',mode:'direct',formats:['3ds','blend','fb','glb','max','maya','stl'],auth:'none'},{name:'printables',mode:'direct',formats:['stl'],auth:'none'},{name:'smithsonian',mode:'direct',formats:['stl','glb','gltf','obj','ply','blend','f3z'],auth:'api-key',configured:Boolean(process.env.SMITHSONIAN_API_KEY)}],special:{name:'3ddd',mode:'latest-link-only',formats:'not exposed by current /api/models/last'}}));
app.get('/latest/3ddd',async(_req,res)=>{try{const results=await get3DDDLatest();res.json({source:'3ddd',count:results.length,results});}catch(e){res.status(502).json({error:'3ddd latest failed',details:String(e?.message||e)});}});
app.get('/diagnostics/search',async(req,res)=>{const parsed=parseQuery(String(req.query.q||''));const format=normFormat(req.query.format||parsed.format)||null;if(!parsed.query)return res.status(400).json({error:'q is required'});const providers=[['printables',searchPrintables],['polypizza',searchPolyPizza],['free3d',searchFree3D],['sketchfab',searchSketchfab],['polyhaven',searchPolyHaven],['nasa',searchNasa],['smithsonian',searchSmithsonian],['3dfetch-fallback',searchFallback]];const out={};for(const [name,fn] of providers){try{const rows=await fn(parsed.query,format);out[name]={ok:true,count:rows.length,examples:rows.slice(0,5).map(x=>({name:x.name,formats:x.formats,url:x.sourceUrl}))};}catch(e){out[name]={ok:false,error:String(e?.message||e)};}}res.json({query:parsed.query,format,providers:out});});
app.get('/search',async(req,res)=>{const parsed=parseQuery(String(req.query.q||''));const format=normFormat(req.query.format||parsed.format)||null;if(!parsed.query)return res.status(400).json({error:'q is required'});try{const results=await searchModels(parsed.query,format);res.json({query:parsed.query,format,count:results.length,results});}catch(e){res.status(502).json({error:'search failed',details:String(e?.message||e)});}});
app.listen(port,'0.0.0.0',()=>console.log(`3D search service listening on port ${port}`));
